MeteorPeak_RestHouse_MapScripts::
	.byte 0

MeteorPeak_RestHouse_WelcomeToChimneysInn::
	msgbox MeteorPeak_RestHouse_Text_WelcomeToChimneysInn, MSGBOX_NPC
	end

MeteorPeak_RestHouse_MyBestYears::
	msgbox MeteorPeak_RestHouse_Text_MyBestYears, MSGBOX_NPC
	end

MeteorPeak_RestHouse_GoingOutSkiing::
	msgbox MeteorPeak_RestHouse_Text_GoingOutSkiing, MSGBOX_NPC
	end

MeteorPeak_RestHouse_NothingLikeANiceWarmBed::
	msgbox MeteorPeak_RestHouse_Text_NothingLikeANiceWarmBed, MSGBOX_NPC
	end

MeteorPeak_RestHouse_Text_WelcomeToChimneysInn:
	.string "Welcome to Chimney's Inn!\p"
	.string "All our beds are full now,\n"
	.string "but we're renovating soon\l"
	.string "to increase our space.$"

MeteorPeak_RestHouse_Text_MyBestYears:
	.string "I knew I shouldn't've climbed\n"
	.string "that mountain.\p"
	.string "I'm not as fit as I once was…$"

MeteorPeak_RestHouse_Text_GoingOutSkiing:
	.string "This inn is the place to be\n"
	.string "for any ski trip!\p"
	.string "You have to book so far in\n"
	.string "advance if you want a bed here!$"

MeteorPeak_RestHouse_Text_NothingLikeANiceWarmBed:
	.string "Ah, nothing like a nice warm\n"
	.string "bed after a chilly hike!$"
