#ifndef GUARD_CONSTANTS_OPPONENTS_H
#define GUARD_CONSTANTS_OPPONENTS_H

#define TRAINER_NONE                          0
#define TRAINER_SAWYER_1                      1
#define TRAINER_GRUNT_AQUA_HIDEOUT_1          2
#define TRAINER_GRUNT_AQUA_HIDEOUT_2          3
#define TRAINER_GRUNT_AQUA_HIDEOUT_3          4
#define TRAINER_GRUNT_AQUA_HIDEOUT_4          5
#define TRAINER_GRUNT_SEAFLOOR_CAVERN_1       6
#define TRAINER_GRUNT_SEAFLOOR_CAVERN_2       7
#define TRAINER_GRUNT_SEAFLOOR_CAVERN_3       8
#define TRAINER_GABRIELLE_1                   9
#define TRAINER_GRUNT_PETALBURG_WOODS        10
#define TRAINER_MARCEL                       11
#define TRAINER_ALBERTO                      12
#define TRAINER_ED                           13
#define TRAINER_GRUNT_SEAFLOOR_CAVERN_4      14
#define TRAINER_DECLAN                       15
#define TRAINER_GRUNT_RUSTURF_TUNNEL         16
#define TRAINER_GRUNT_WEATHER_INST_1         17
#define TRAINER_GRUNT_WEATHER_INST_2         18
#define TRAINER_GRUNT_WEATHER_INST_3         19
#define TRAINER_GRUNT_MUSEUM_1               20
#define TRAINER_GRUNT_MUSEUM_2               21
#define TRAINER_GRUNT_SPACE_CENTER_1         22
#define TRAINER_GRUNT_MT_PYRE_1              23
#define TRAINER_GRUNT_MT_PYRE_2              24
#define TRAINER_GRUNT_MT_PYRE_3              25
#define TRAINER_GRUNT_WEATHER_INST_4         26
#define TRAINER_GRUNT_AQUA_HIDEOUT_5         27
#define TRAINER_GRUNT_AQUA_HIDEOUT_6         28
#define TRAINER_FREDRICK                     29
#define TRAINER_MATT                         30
#define TRAINER_ZANDER                       31
#define TRAINER_SHELLY_WEATHER_INSTITUTE     32
#define TRAINER_SHELLY_SEAFLOOR_CAVERN       33
#define TRAINER_ARCHIE                       34
#define TRAINER_LEAH                         35
#define TRAINER_DAISY                        36
#define TRAINER_ROSE_1                       37
#define TRAINER_FELIX                        38
#define TRAINER_VIOLET                       39
#define TRAINER_DUSTY_1                      40
#define TRAINER_CHIP                         41
#define TRAINER_FOSTER                       42
#define TRAINER_GABBY_AND_TY_1               43
#define TRAINER_GABBY_AND_TY_2               44
#define TRAINER_GABBY_AND_TY_3               45
#define TRAINER_GABBY_AND_TY_4               46
#define TRAINER_GABBY_AND_TY_5               47
#define TRAINER_GABBY_AND_TY_6               48
#define TRAINER_LOLA_1                       49
#define TRAINER_AUSTINA                      50
#define TRAINER_GWEN                         51
#define TRAINER_RICKY_1                      52
#define TRAINER_SIMON                        53
#define TRAINER_CHARLIE                      54
#define TRAINER_RANDALL                      55
#define TRAINER_PARKER                       56
#define TRAINER_GEORGE                       57
#define TRAINER_BERKE                        58
#define TRAINER_BRAXTON                      59
#define TRAINER_VINCENT                      60
#define TRAINER_LEROY                        61
#define TRAINER_WILTON_1                     62
#define TRAINER_EDGAR                        63
#define TRAINER_ALBERT                       64
#define TRAINER_SAMUEL                       65
#define TRAINER_VITO                         66
#define TRAINER_OWEN                         67
#define TRAINER_WARREN                       68
#define TRAINER_MARY                         69
#define TRAINER_ALEXIA                       70
#define TRAINER_JODY                         71
#define TRAINER_WENDY                        72
#define TRAINER_KEIRA                        73
#define TRAINER_BROOKE_1                     74
#define TRAINER_JENNIFER                     75
#define TRAINER_HOPE                         76
#define TRAINER_SHANNON                      77
#define TRAINER_MICHELLE                     78
#define TRAINER_CAROLINE                     79
#define TRAINER_JULIE                        80
#define TRAINER_PATRICIA                     81
#define TRAINER_KINDRA                       82
#define TRAINER_TAMMY                        83
#define TRAINER_VALERIE_1                    84
#define TRAINER_TASHA                        85
#define TRAINER_CINDY_1                      86
#define TRAINER_DAPHNE                       87
#define TRAINER_GRUNT_SPACE_CENTER_2         88
#define TRAINER_BRIANNA                      89
#define TRAINER_NAOMI                        90
#define TRAINER_MELISSA                      91
#define TRAINER_SHEILA                       92
#define TRAINER_SHIRLEY                      93
#define TRAINER_JESSICA_1                    94
#define TRAINER_CONNIE                       95
#define TRAINER_BRIDGET                      96
#define TRAINER_OLIVIA                       97
#define TRAINER_TIFFANY                      98
#define TRAINER_WINSTON_1                    99
#define TRAINER_MOLLIE                      100
#define TRAINER_GARRET                      101
#define TRAINER_STEVE_1                     102
#define TRAINER_THALIA_1                    103
#define TRAINER_MARK                        104
#define TRAINER_GRUNT_MT_CHIMNEY_1          105
#define TRAINER_LUIS                        106
#define TRAINER_DOMINIK                     107
#define TRAINER_DOUGLAS                     108
#define TRAINER_DARRIN                      109
#define TRAINER_TONY_1                      110
#define TRAINER_JEROME                      111
#define TRAINER_MATTHEW                     112
#define TRAINER_DAVID                       113
#define TRAINER_SPENCER                     114
#define TRAINER_ROLAND                      115
#define TRAINER_NOLEN                       116
#define TRAINER_STAN                        117
#define TRAINER_BARRY                       118
#define TRAINER_DEAN                        119
#define TRAINER_RODNEY                      120
#define TRAINER_RICHARD                     121
#define TRAINER_HERMAN                      122
#define TRAINER_SANTIAGO                    123
#define TRAINER_GILBERT                     124
#define TRAINER_FRANKLIN                    125
#define TRAINER_KEVIN                       126
#define TRAINER_JACK                        127
#define TRAINER_DUDLEY                      128
#define TRAINER_CHAD                        129
#define TRAINER_TAKAO                       130
#define TRAINER_HITOSHI                     131
#define TRAINER_KIYO                        132
#define TRAINER_KOICHI                      133
#define TRAINER_NOB_1                       134
#define TRAINER_YUJI                        135
#define TRAINER_DAISUKE                     136
#define TRAINER_ATSUSHI                     137
#define TRAINER_KIRK                        138
#define TRAINER_GRUNT_AQUA_HIDEOUT_7        139
#define TRAINER_GRUNT_AQUA_HIDEOUT_8        140
#define TRAINER_SHAWN                       141
#define TRAINER_FERNANDO_1                  142
#define TRAINER_DALTON_1                    143
#define TRAINER_COLE                        144
#define TRAINER_JEFF                        145
#define TRAINER_AXLE                        146
#define TRAINER_JACE                        147
#define TRAINER_KEEGAN                      148
#define TRAINER_BERNIE_1                    149
#define TRAINER_DREW                        150
#define TRAINER_BEAU                        151
#define TRAINER_LARRY                       152
#define TRAINER_SHANE                       153
#define TRAINER_JUSTIN                      154
#define TRAINER_ETHAN_1                     155
#define TRAINER_AUTUMN                      156
#define TRAINER_TRAVIS                      157
#define TRAINER_BRENT                       158
#define TRAINER_DONALD                      159
#define TRAINER_TAYLOR                      160
#define TRAINER_JEFFREY_1                   161
#define TRAINER_DEREK                       162
#define TRAINER_EDWARD                      163
#define TRAINER_PRESTON                     164
#define TRAINER_VIRGIL                      165
#define TRAINER_BLAKE                       166
#define TRAINER_WILLIAM                     167
#define TRAINER_JOSHUA                      168
#define TRAINER_CAMERON_1                   169
#define TRAINER_JACLYN                      170
#define TRAINER_HANNAH                      171
#define TRAINER_SAMANTHA                    172
#define TRAINER_MAURA                       173
#define TRAINER_KAYLA                       174
#define TRAINER_ALEXIS                      175
#define TRAINER_JACKI_1                     176
#define TRAINER_WALTER_1                    177
#define TRAINER_MICAH                       178
#define TRAINER_THOMAS                      179
#define TRAINER_SIDNEY                      180
#define TRAINER_PHOEBE                      181
#define TRAINER_GLACIA                      182
#define TRAINER_DRAKE                       183
#define TRAINER_ROXANNE                     184
#define TRAINER_BRAWLY                      185
#define TRAINER_WATTSON                     186
#define TRAINER_FLANNERY                    187
#define TRAINER_NORMAN                      188
#define TRAINER_WINONA                      189
#define TRAINER_TATE_AND_LIZA               190
#define TRAINER_JUAN                        191
#define TRAINER_JERRY_1                     192
#define TRAINER_TED                         193
#define TRAINER_PAUL                        194
#define TRAINER_KAREN_1                     195
#define TRAINER_GEORGIA                     196
#define TRAINER_KATE_AND_JOY                197
#define TRAINER_ANNA_AND_MEG_1              198
#define TRAINER_VICTOR                      199
#define TRAINER_MIGUEL_1                    200
#define TRAINER_COLTON                      201
#define TRAINER_VICTORIA                    202
#define TRAINER_VANESSA                     203
#define TRAINER_BETHANY                     204
#define TRAINER_ISABEL_1                    205
#define TRAINER_TIMOTHY_1                   206
#define TRAINER_VICKY                       207
#define TRAINER_SHELBY_1                    208
#define TRAINER_CALVIN_1                    209
#define TRAINER_BILLY                       210
#define TRAINER_JOSH                        211
#define TRAINER_TOMMY                       212
#define TRAINER_JOEY                        213
#define TRAINER_BEN                         214
#define TRAINER_QUINCY                      215
#define TRAINER_KATELYNN                    216
#define TRAINER_JAYLEN                      217
#define TRAINER_DILLON                      218
#define TRAINER_EDDIE                       219
#define TRAINER_ALLEN                       220
#define TRAINER_TIMMY                       221
#define TRAINER_WALLACE                     222
#define TRAINER_ANDREW                      223
#define TRAINER_IVAN                        224
#define TRAINER_CLAUDE                      225
#define TRAINER_ELLIOT_1                    226
#define TRAINER_NED                         227
#define TRAINER_DALE                        228
#define TRAINER_NOLAN                       229
#define TRAINER_BARNY                       230
#define TRAINER_WADE                        231
#define TRAINER_CARTER                      232
#define TRAINER_RONALD                      233
#define TRAINER_JACOB                       234
#define TRAINER_ANTHONY                     235
#define TRAINER_BENJAMIN_1                  236
#define TRAINER_ABIGAIL_1                   237
#define TRAINER_JASMINE                     238
#define TRAINER_DYLAN_1                     239
#define TRAINER_MARIA_1                     240
#define TRAINER_CAMDEN                      241
#define TRAINER_DEMETRIUS                   242
#define TRAINER_ISAIAH_1                    243
#define TRAINER_PABLO_1                     244
#define TRAINER_CHASE                       245
#define TRAINER_ISOBEL                      246
#define TRAINER_DONNY                       247
#define TRAINER_TALIA                       248
#define TRAINER_KATELYN_1                   249
#define TRAINER_ALLISON                     250
#define TRAINER_NICOLAS_1                   251
#define TRAINER_AARON                       252
#define TRAINER_PERRY                       253
#define TRAINER_HUGH                        254
#define TRAINER_PHIL                        255
#define TRAINER_JARED                       256
#define TRAINER_HUMBERTO                    257
#define TRAINER_PRESLEY                     258
#define TRAINER_EDWARDO                     259
#define TRAINER_COLIN                       260
#define TRAINER_ROBERT_1                    261
#define TRAINER_BENNY                       262
#define TRAINER_CHESTER                     263
#define TRAINER_ALEX                        264
#define TRAINER_BECK                        265
#define TRAINER_YASU                        266
#define TRAINER_TAKASHI                     267
#define TRAINER_DIANNE                      268
#define TRAINER_JANI                        269
#define TRAINER_LAO_1                       270
#define TRAINER_LUNG                        271
#define TRAINER_JOCELYN                     272
#define TRAINER_LAURA                       273
#define TRAINER_CYNDY_1                     274
#define TRAINER_CORA                        275
#define TRAINER_PAULA                       276
#define TRAINER_MADELINE_1                  277
#define TRAINER_CLARISSA                    278
#define TRAINER_ANGELICA                    279
#define TRAINER_BEVERLY                     280
#define TRAINER_IMANI                       281
#define TRAINER_KYLA                        282
#define TRAINER_DENISE                      283
#define TRAINER_BETH                        284
#define TRAINER_TARA                        285
#define TRAINER_MISSY                       286
#define TRAINER_ALICE                       287
#define TRAINER_JENNY_1                     288
#define TRAINER_GRACE                       289
#define TRAINER_TANYA                       290
#define TRAINER_SHARON                      291
#define TRAINER_NIKKI                       292
#define TRAINER_BRENDA                      293
#define TRAINER_KATIE                       294
#define TRAINER_SUSIE                       295
#define TRAINER_KARA                        296
#define TRAINER_DANA                        297
#define TRAINER_SIENNA                      298
#define TRAINER_DEBRA                       299
#define TRAINER_LINDA                       300
#define TRAINER_KAYLEE                      301
#define TRAINER_LAUREL                      302
#define TRAINER_CARLEE                      303
#define TRAINER_HEIDI                       304
#define TRAINER_BECKY                       305
#define TRAINER_CAROL                       306
#define TRAINER_NANCY                       307
#define TRAINER_MARTHA                      308
#define TRAINER_DIANA_1                     309
#define TRAINER_CEDRIC                      310
#define TRAINER_IRENE                       311
#define TRAINER_AMY_AND_LIV_1               312
#define TRAINER_GINA_AND_MIA_1              313
#define TRAINER_MIU_AND_YUKI                314
#define TRAINER_HUEY                        315
#define TRAINER_EDMOND                      316
#define TRAINER_ERNEST_1                    317
#define TRAINER_DWAYNE                      318
#define TRAINER_PHILLIP                     319
#define TRAINER_LEONARD                     320
#define TRAINER_DUNCAN                      321
#define TRAINER_ELI                         322
#define TRAINER_ANNIKA                      323
#define TRAINER_JAZMYN                      324
#define TRAINER_JONAS                       325
#define TRAINER_KAYLEY                      326
#define TRAINER_AURON                       327
#define TRAINER_KELVIN                      328
#define TRAINER_MARLEY                      329
#define TRAINER_REYNA                       330
#define TRAINER_HUDSON                      331
#define TRAINER_CONOR                       332
#define TRAINER_EDWIN_1                     333
#define TRAINER_HECTOR                      334
#define TRAINER_TABITHA_MOSSDEEP            335
#define TRAINER_WALLY_VR_1                  336
#define TRAINER_BRENDAN_ROUTE_103_MUDKIP    337
#define TRAINER_BRENDAN_ROUTE_110_MUDKIP    338
#define TRAINER_BRENDAN_ROUTE_119_MUDKIP    339
#define TRAINER_BRENDAN_ROUTE_103_TREECKO   340
#define TRAINER_BRENDAN_ROUTE_110_TREECKO   341
#define TRAINER_BRENDAN_ROUTE_119_TREECKO   342
#define TRAINER_BRENDAN_ROUTE_103_TORCHIC   343
#define TRAINER_BRENDAN_ROUTE_110_TORCHIC   344
#define TRAINER_BRENDAN_ROUTE_119_TORCHIC   345
#define TRAINER_MAY_ROUTE_103_MUDKIP        346
#define TRAINER_MAY_ROUTE_110_MUDKIP        347
#define TRAINER_MAY_ROUTE_119_MUDKIP        348
#define TRAINER_MAY_ROUTE_103_TREECKO       349
#define TRAINER_MAY_ROUTE_110_TREECKO       350
#define TRAINER_MAY_ROUTE_119_TREECKO       351
#define TRAINER_MAY_ROUTE_103_TORCHIC       352
#define TRAINER_MAY_ROUTE_110_TORCHIC       353
#define TRAINER_MAY_ROUTE_119_TORCHIC       354
#define TRAINER_ISAAC_1                     355
#define TRAINER_DAVIS                       356
#define TRAINER_MITCHELL                    357
#define TRAINER_LYDIA_1                     358
#define TRAINER_HALLE                       359
#define TRAINER_GARRISON                    360
#define TRAINER_JACKSON_1                   361
#define TRAINER_LORENZO                     362
#define TRAINER_SEBASTIAN                   363
#define TRAINER_CATHERINE_1                 364
#define TRAINER_JENNA                       365
#define TRAINER_SOPHIA                      366
#define TRAINER_JULIO                       367
#define TRAINER_GRUNT_SEAFLOOR_CAVERN_5     368
#define TRAINER_MIKE_2                      369
#define TRAINER_GRUNT_MT_PYRE_4             370
#define TRAINER_GRUNT_JAGGED_PASS           371
#define TRAINER_MARC                        372
#define TRAINER_BRENDEN                     373
#define TRAINER_LILITH                      374
#define TRAINER_CRISTIAN                    375
#define TRAINER_SYLVIA                      376
#define TRAINER_LEONARDO                    377
#define TRAINER_ATHENA                      378
#define TRAINER_HARRISON                    379
#define TRAINER_GRUNT_MT_CHIMNEY_2          380
#define TRAINER_CLARENCE                    381
#define TRAINER_TERRY                       382
#define TRAINER_NATE                        383
#define TRAINER_KATHLEEN                    384
#define TRAINER_CLIFFORD                    385
#define TRAINER_NICHOLAS                    386
#define TRAINER_GRUNT_SPACE_CENTER_3        387
#define TRAINER_GRUNT_SPACE_CENTER_4        388
#define TRAINER_GRUNT_SPACE_CENTER_5        389
#define TRAINER_GRUNT_SPACE_CENTER_6        390
#define TRAINER_GRUNT_SPACE_CENTER_7        391
#define TRAINER_MACEY                       392
#define TRAINER_BRENDAN_RUSTBORO_TREECKO    393
#define TRAINER_BRENDAN_RUSTBORO_MUDKIP     394
#define TRAINER_PAXTON                      395
#define TRAINER_ISABELLA                    396
#define TRAINER_GRUNT_WEATHER_INST_5        397
#define TRAINER_TABITHA_MT_CHIMNEY          398
#define TRAINER_JONATHAN                    399
#define TRAINER_BRENDAN_RUSTBORO_TORCHIC    400
#define TRAINER_MAY_RUSTBORO_MUDKIP         401
#define TRAINER_MAXIE_MAGMA_HIDEOUT         402
#define TRAINER_MAXIE_MT_CHIMNEY            403
#define TRAINER_TIANA                       404
#define TRAINER_HALEY_1                     405
#define TRAINER_JANICE                      406
#define TRAINER_VIVI                        407
#define TRAINER_SALLY                       408
#define TRAINER_ROBIN                       409
#define TRAINER_ANDREA                      410
#define TRAINER_CRISSY                      411
#define TRAINER_RICK                        412
#define TRAINER_LYLE                        413
#define TRAINER_JOSE                        414
#define TRAINER_DOUG                        415
#define TRAINER_GREG                        416
#define TRAINER_KENT                        417
#define TRAINER_JAMES_1                     418
#define TRAINER_BRICE                       419
#define TRAINER_TRENT_1                     420
#define TRAINER_LENNY                       421
#define TRAINER_LUCAS_1                     422
#define TRAINER_ALAN                        423
#define TRAINER_CLARK                       424
#define TRAINER_ERIC                        425
#define TRAINER_COURTNEY_CRATERCREST        426
#define TRAINER_MIKE_1                      427
#define TRAINER_DEZ_AND_LUKE                428
#define TRAINER_LEA_AND_JED                 429
#define TRAINER_KIRA_AND_DAN_1              430
#define TRAINER_JOHANNA                     431
#define TRAINER_GERALD                      432
#define TRAINER_VIVIAN                      433
#define TRAINER_DANIELLE                    434
#define TRAINER_HIDEO                       435
#define TRAINER_KEIGO                       436
#define TRAINER_RILEY                       437
#define TRAINER_FLINT                       438
#define TRAINER_ASHLEY                      439
#define TRAINER_WALLY_MAUVILLE              440
#define TRAINER_WALLY_VR_2                  441
#define TRAINER_WALLY_VR_3                  442
#define TRAINER_WALLY_VR_4                  443
#define TRAINER_WALLY_VR_5                  444
#define TRAINER_BRENDAN_LILYCOVE_MUDKIP     445
#define TRAINER_BRENDAN_LILYCOVE_TREECKO    446
#define TRAINER_BRENDAN_LILYCOVE_TORCHIC    447
#define TRAINER_MAY_LILYCOVE_MUDKIP         448
#define TRAINER_MAY_LILYCOVE_TREECKO        449
#define TRAINER_MAY_LILYCOVE_TORCHIC        450
#define TRAINER_JONAH                       451
#define TRAINER_HENRY                       452
#define TRAINER_ROGER                       453
#define TRAINER_ALEXA                       454
#define TRAINER_RUBEN                       455
#define TRAINER_KOJI_1                      456
#define TRAINER_WAYNE                       457
#define TRAINER_AIDAN                       458
#define TRAINER_REED                        459
#define TRAINER_TISHA                       460
#define TRAINER_TORI_AND_TIA                461
#define TRAINER_KIM_AND_IRIS                462
#define TRAINER_TYRA_AND_IVY                463
#define TRAINER_MEL_AND_PAUL                464
#define TRAINER_JOHN_AND_JAY_1              465
#define TRAINER_RELI_AND_IAN                466
#define TRAINER_LILA_AND_ROY_1              467
#define TRAINER_LISA_AND_RAY                468
#define TRAINER_CHRIS                       469
#define TRAINER_DAWSON                      470
#define TRAINER_SARAH                       471
#define TRAINER_DARIAN                      472
#define TRAINER_HAILEY                      473
#define TRAINER_CHANDLER                    474
#define TRAINER_KALEB                       475
#define TRAINER_JOSEPH                      476
#define TRAINER_ALYSSA                      477
#define TRAINER_MARCOS                      478
#define TRAINER_RHETT                       479
#define TRAINER_TYRON                       480
#define TRAINER_CELINA                      481
#define TRAINER_BIANCA                      482
#define TRAINER_HAYDEN                      483
#define TRAINER_SOPHIE                      484
#define TRAINER_COBY                        485
#define TRAINER_LAWRENCE                    486
#define TRAINER_WYATT                       487
#define TRAINER_ANGELINA                    488
#define TRAINER_KAI                         489
#define TRAINER_CHARLOTTE                   490
#define TRAINER_DEANDRE                     491
#define TRAINER_GRUNT_MAGMA_HIDEOUT_1       492
#define TRAINER_GRUNT_MAGMA_HIDEOUT_2       493
#define TRAINER_GRUNT_MAGMA_HIDEOUT_3       494
#define TRAINER_GRUNT_MAGMA_HIDEOUT_4       495
#define TRAINER_GRUNT_MAGMA_HIDEOUT_5       496
#define TRAINER_GRUNT_MAGMA_HIDEOUT_6       497
#define TRAINER_GRUNT_MAGMA_HIDEOUT_7       498
#define TRAINER_GRUNT_MAGMA_HIDEOUT_8       499
#define TRAINER_GRUNT_MAGMA_HIDEOUT_9       500
#define TRAINER_GRUNT_MAGMA_HIDEOUT_10      501
#define TRAINER_GRUNT_MAGMA_HIDEOUT_11      502
#define TRAINER_GRUNT_MAGMA_HIDEOUT_12      503
#define TRAINER_GRUNT_MAGMA_HIDEOUT_13      504
#define TRAINER_GRUNT_MAGMA_HIDEOUT_14      505
#define TRAINER_GRUNT_MAGMA_HIDEOUT_15      506
#define TRAINER_GRUNT_MAGMA_HIDEOUT_16      507
#define TRAINER_TABITHA_MAGMA_HIDEOUT       508
#define TRAINER_DARCY                       509
#define TRAINER_MAXIE_MOSSDEEP              510
#define TRAINER_PETE                        511
#define TRAINER_ISABELLE                    512
#define TRAINER_ANDRES_1                    513
#define TRAINER_JOSUE                       514
#define TRAINER_CAMRON                      515
#define TRAINER_CORY_1                      516
#define TRAINER_CAROLINA                    517
#define TRAINER_ELIJAH                      518
#define TRAINER_CELIA                       519
#define TRAINER_BRYAN                       520
#define TRAINER_BRANDEN                     521
#define TRAINER_BRYANT                      522
#define TRAINER_SHAYLA                      523
#define TRAINER_KYRA                        524
#define TRAINER_JAIDEN                      525
#define TRAINER_ALIX                        526
#define TRAINER_HELENE                      527
#define TRAINER_MARLENE                     528
#define TRAINER_DEVAN                       529
#define TRAINER_JOHNSON                     530
#define TRAINER_MELINA                      531
#define TRAINER_BRANDI                      532
#define TRAINER_AISHA                       533
#define TRAINER_MAKAYLA                     534
#define TRAINER_FABIAN                      535
#define TRAINER_DAYTON                      536
#define TRAINER_RACHEL                      537
#define TRAINER_LEONEL                      538
#define TRAINER_CALLIE                      539
#define TRAINER_CALE                        540
#define TRAINER_MYLES                       541
#define TRAINER_PAT                         542
#define TRAINER_CRISTIN_1                   543
#define TRAINER_MAY_RUSTBORO_TREECKO        544
#define TRAINER_MAY_RUSTBORO_TORCHIC        545
#define TRAINER_ROXANNE_REMATCH             546
#define TRAINER_BRAWLY_REMATCH              547
#define TRAINER_WATTSON_REMATCH             548
#define TRAINER_FLANNERY_REMATCH            549
#define TRAINER_NORMAN_REMATCH              550
#define TRAINER_WINONA_REMATCH              551
#define TRAINER_TATE_AND_LIZA_REMATCH       552
#define TRAINER_JUAN_REMATCH                553
#define TRAINER_ANGELO                      554
#define TRAINER_DARIUS                      555
#define TRAINER_STEVEN                      556
#define TRAINER_ANABEL                      557
#define TRAINER_TUCKER                      558
#define TRAINER_SPENSER                     559
#define TRAINER_GRETA                       560
#define TRAINER_NOLAND                      561
#define TRAINER_LUCY                        562
#define TRAINER_BRANDON                     563
#define TRAINER_MARIELA                     564
#define TRAINER_ALVARO                      565
#define TRAINER_EVERETT                     566
#define TRAINER_RED                         567
#define TRAINER_LEAF                        568
#define TRAINER_BRENDAN_PLACEHOLDER         569
#define TRAINER_MAY_PLACEHOLDER             570
#define TRAINER_SMITH                       571
#define TRAINER_IZZY                        572
#define TRAINER_JEREMIAH                    573
#define TRAINER_ADRIAN                      574
#define TRAINER_LUCA                        575
#define TRAINER_KRISTI                      576
#define TRAINER_VANYA                       577
#define TRAINER_LUNA                        578
#define TRAINER_KINGSTON                    579
#define TRAINER_AJAX                        580
#define TRAINER_OPAL                        581
#define TRAINER_DONOVAN                     582
#define TRAINER_ROSS                        583
#define TRAINER_VINNIE                      584
#define TRAINER_MIRA                        585
#define TRAINER_NOAH                        586
#define TRAINER_AUSTIN                      587
#define TRAINER_LANDON                      588
#define TRAINER_ELIAS                       589
#define TRAINER_HARPER                      590
#define TRAINER_EVELYN                      591
#define TRAINER_MILES                       592
#define TRAINER_VLAD                        593
#define TRAINER_ERIK                        594
#define TRAINER_SASHA                       595
#define TRAINER_LEO                         596
#define TRAINER_SHAE                        597
#define TRAINER_PEARL                       598
#define TRAINER_MATEO                       599
#define TRAINER_SHANIA                      600
#define TRAINER_MARIANA                     601
#define TRAINER_PATRICK                     602
#define TRAINER_MILO                        603
#define TRAINER_KATERINA                    604
#define TRAINER_EMMA                        605
#define TRAINER_ARTYOM                      606

// NOTE: Because each Trainer uses a flag to determine when they are defeated, there is only space for 9 additional trainers before trainer flag space overflows
//       More space can be made by shifting flags around in constants/flags.h or changing how trainer flags are handled
//       MAX_TRAINERS_COUNT can be increased but will take up additional saveblock space

#define TRAINERS_COUNT                      607
#define MAX_TRAINERS_COUNT                  864

#endif  // GUARD_CONSTANTS_OPPONENTS_H
