CratercrestTown_House1_MapScripts::
	.byte 0

CratercrestTown_House1_EventScript_WhatsWithTeamMagma::
	msgbox CratercrestTown_House1_Text_WhatsWithTeamMagma, MSGBOX_NPC
	end

CratercrestTown_House1_EventScript_IJustWannaHike::
	msgbox CratercrestTown_House1_Text_IJustWannaHike, MSGBOX_NPC
	end

CratercrestTown_House1_Text_WhatsWithTeamMagma:
	.string "What's with Team Magma!?\p"
	.string "They come in, drill into\n"
	.string "the side of the mountain,\p"
	.string "and have been terrorizing\n"
	.string "the town ever since!\p"
	.string "Can't they just bug off?$"

CratercrestTown_House1_Text_IJustWannaHike:
	.string "We moved here for the many\n"
	.string "trails between Mt. Chimney\l"
	.string "and Mt. Meteor.\p"
	.string "But ever since Team Magma set\n"
	.string "up shop here, Mt. Chimney has\l"
	.string "been dangerously unstable.\p"
	.string "I just wanna hike, man...$"
