CratercrestTown_House1_MapScripts::
	.byte 0

CratercrestTown_House1_EventScript_WhatsWithTeamMagma::
	msgbox CratercrestTown_House1_Text_WhatsWithTeamMagma, MSGBOX_NPC
	end

CratercrestTown_House1_EventScript_IJustWannaHike::
	msgbox CratercrestTown_House1_Text_IJustWannaHike, MSGBOX_NPC
	end

CratercrestTown_House1_Text_WhatsWithTeamMagma:
	.string "What's with Team Magma!?\p"
	.string "They come in, drill into the side of\n"
	.string "the mountain, and they've been\l"
	.string "terrorizing the town ever since!\p"
	.string "Can't they just bug off?$"

CratercrestTown_House1_Text_IJustWannaHike:
	.string "We moved here for the many trails\n"
	.string "between Mt. Chimney and Mt. Meteor.\p"
	.string "But ever since Team Magma set up shop\n"
	.string "here, Mt. Chimney has been dangerously\l"
	.string "unstable.\p"
	.string "I just wanna hike, man...$"
