Common_EventScript_FindItem::
	callnative GetItemBallIdAndAmountFromTemplate
	finditem VAR_RESULT VAR_0x8009
	end

AwakeningWoods_EventScript_ItemOldGateau:: @ 829152C
	finditem ITEM_OLD_GATEAU
	end

AwakeningWoods_EventScript_ItemStick:: @ 829152C
	finditem ITEM_LEEK
	end

AwakeningWoods_EventScript_ItemDampRock:: @ 829152C
	finditem ITEM_DAMP_ROCK
	end

AwakeningWoods_EventScript_ItemHeatRock:: @ 829152C
	finditem ITEM_HEAT_ROCK
	end

AwakeningWoods_EventScript_ItemIcyRock:: @ 829152C
	finditem ITEM_ICY_ROCK
	end

AwakeningWoods_EventScript_ItemSmoothRock:: @ 829152C
	finditem ITEM_SMOOTH_ROCK
	end
